import java.util.*;
/**
 * 09/08/2022
 */
public class Leetcode279 {
    /**
     * Leetcode 279 - Perfect Squares (Medium)
     * TC: O(n)
     * SC: O(n)
     * Share similar idea with Leetcode 332 with coins array generated by all
     * possible perfect squares smaller than given number.
     */
    public int numSquares(int n) {
        int[] dp = new int[n + 1];
        int[] square = new int[(int)Math.sqrt(n)];
        for (int i = 0; i < square.length; i++) {
            square[i] = (i + 1) * (i + 1);
        }
        Arrays.fill(dp, n + 1);
        dp[0] = 0;
        for (int i = 1; i <= n; i++) {
            for (int j = 0; j < square.length; j++) {
                if (square[j] <= i) {
                    dp[i] = Math.min(dp[i], dp[i - square[j]] + 1);
                }
            }
        }
        return dp[n] > n ? n : dp[n];
    }
}
